### ISSUE TITLE
Impossible to run in background

### ISSUE THREAD

**Issue by photopea** [kzahel/web-server-chrome#34]
When I check the "Run in background" checkbox and close the "Web Server For Chrome" window of your extension. My website on http://127.0.0.1:8887/ still works for a while, but after some time (e.g. after a minute) if you reload the page, Chrome shows "ERR_CONNECTION_REFUSED".

Can you fix it, so the window of your plugin does not have to be open constantly in a task bar?

**Comment by kzahel** [comment]
This is something that I'm not really sure I can fix. I think if you're using windows, chrome allows apps to run in the background for longer, but on ChromeOS and on low RAM machines (like 2gb) chrome forces apps to suspend pretty aggressively when there is no visible UI surface. This is something that I don't yet fully understand, and I'm not sure of any foolproof methods to really force an app to stay open. I would love to figure this out, though...

**Comment by kzahel** [comment]
Hi. I just put out a new version which should fix the background issue

**Comment by photopea** [comment]
Just removed and installed extension again. Still gets disabled in background :(

**Comment by kzahel** [comment]
Did you click on the options "run in background" and "auto start" ?

**Comment by photopea** [comment]
Yes, both options are enabled. I use Chrome 48.0.2564.109 m on Windows 7.

**Comment by kzahel** [comment]
Hm. I tested on Windows 8 with Chrome 48 and it continues to run in the background for me. I can't imagine that Windows 7 would make a big difference here. I'm stumped..

**Comment by kzahel** [comment]
Also you could perhaps try restarting the app after changing those settings

**Comment by photopea** [comment]
Hi, now HTTP server is still on, few hours after closing window. So I think it should be solved. Thank you.
